packages: []

lockfile: false

onlyBuiltDependencies:
  - '@karinjs/node-pty'
  - '@karinjs/sqlite3-cjs'
  - canvas
  - classic-level
  - esbuild
  - puppeteer
  - sharp
  - sqlite3

publicHoistPattern:
  - '*sqlite3*'
  - '*express*'
